Surf_blog/Surf_blog/Controllers/FeedController.cs
using Surf_blog.DAL;
using Surf_blog.Helpers;
using Surf_blog.Models.DBModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Surf_blog.Controllers
{
    public class FeedController : Controller
    {
        private SurfDBContext dBContext = new SurfDBContext();
        // GET: Feed
        public ActionResult Index()
        {
            var posts = dBContext.Posts.OrderByDescending(c => c.Id).ToList();
            ViewBag.Posts = posts;

            return View();
        }

        [HttpPost]
        public ActionResult AddPost(Post model, HttpPostedFileBase imageData)
        {
            if (!ModelState.IsValid)
            {
                var posts1 = dBContext.Posts.OrderByDescending(c => c.Id).ToList();
                ViewBag.Posts = posts1;
                return View("Index", model);
            }
            if (imageData == null && model.Text == null)
            {
                ModelState.AddModelError(string.Empty, "Не загружено изображение или отсутствует текст");
                var posts1 = dBContext.Posts.OrderByDescending(c => c.Id).ToList();
                ViewBag.Posts = posts1;
                return View("Index", model);
            }

            model.PublishDate = DateTime.Now;

            if (imageData != null)
            {
                if (!ImageFormatHelper.IsJpg(imageData))
                {
                    ModelState.AddModelError(string.Empty, "Загруженное изображение не jpeg");
                    var posts1 = dBContext.Posts.OrderByDescending(c => c.Id).ToList();
                    ViewBag.Posts = posts1;
                    return View("Index", model);
                }
                model.Photo = ImageSaveHelper.SaveImage(imageData);
            }

            var userId = Convert.ToInt32(Session["UserId"]);
            var userInDb = dBContext.Users.FirstOrDefault(c => c.Id == userId);

            if (userInDb == null)
            {
                TempData["errorMessage"] = "Время сессии истекло. Авторизуйтесь повторно.";
                return RedirectToAction("Index", "Home");
            }

            model.Author = userInDb;

            dBContext.Posts.Add(model);
            dBContext.SaveChanges();
            var posts = dBContext.Posts.OrderByDescending(c => c.Id).ToList();
            ViewBag.Posts = posts;

            ModelState.Clear();

            return View("Index");
        }
    }
}

Surf_blog/Surf_blog/Views/Feed/Index.cshtml
@using Surf_blog.Models.DBModels
@model Surf_blog.Models.DBModels.Post
@{
    ViewBag.Title = "Клуб любителей серфинга - лента новостей";
}

@if (Session["UserId"] != null)
{

    using (Html.BeginForm("AddPost", "Feed", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <label>Добавление новой записи</label>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            <div class="panel-body">
                @Html.ValidationMessageFor(model => model.Text)
                <br />
                @Html.LabelFor(model => model.Text)
                @Html.TextAreaFor(model => model.Text, 5, 100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.LabelFor(model => model.Photo)
                <input name="imageData" type="file" accept="image/jpeg" />
                <button type="submit" class="btn btn-default pull-right">Добавить</button>
            </div>
        </div>
    }
}

@foreach (var post in ViewBag.Posts)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                @{
                    var photoUrl = Surf_blog.Helpers.ImageUrlHelper.GetUrl(post.Author.Photo);
                    if (photoUrl != null)
                    {
                        <div class="col-xs-1">
                            <img class="img-circle" src="@Url.Content(photoUrl)" height="37" width="37" />
                        </div>
                    }
                }
                <div class="col-xs-11">
                    <label class="black-label">@post.Author.Nickname</label>
                    <br>
                    <label class="date-label">@post.PublishDate</label>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <p class="wrap">@post.Text</p>
            @{
                var postPhotoUrl = Surf_blog.Helpers.ImageUrlHelper.GetUrl(post.Photo);
                if (postPhotoUrl != null)
                {
                    <img class="post-img" src="@Url.Content(postPhotoUrl)" />
                }
            }
        </div>
        <div class="panel-footer"></div>
    </div>
}